import express from "express";
import bodyValidator from "../../services/validator.middleware";
import { CreateBlogValidation } from "./blog.validations";
import { authenticateToken } from "../auth/auth.middleware";
const router = express.Router();
import { createBlog, ListAllBlogs, GetMyBlogs, BlogDetailById, BlogDetailBySlug, BlogUpdateById, BlogDeleteById, } from "./blog.controller";
router.get("", ListAllBlogs);
router.get("/me", authenticateToken, GetMyBlogs);
router.post("/create", authenticateToken, bodyValidator(CreateBlogValidation), createBlog);
router.get("/:id", BlogDetailById);
router.get("/slug/:slug", BlogDetailBySlug);
router.put("/:id", authenticateToken, BlogUpdateById);
router.delete("/:id", authenticateToken, BlogDeleteById);
export default router;
